name: Build

on: push
#  push:
#    # Publish `master` as Docker `latest` image.
#    branches:
#      - master
#
#    # Publish `v1.2.3` tags as releases.
#    tags:
#      - v*
#
#  # Run tests for any PRs.
#  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: make build_agent
      - name: Test
        run: SKIP_UPDATES=true go test -v ./...

  build:
    needs: test
    runs-on: self-hosted
    steps:
      - run: aws s3 cp trex.py s3://updates.sysward.com/
      - run: aws s3 cp sysward s3://updates.sysward.com/
      - run: aws cloudfront create-invalidation --distribution-id EXAQZU7A32C2T --paths='/*'